### ISSUE TITLE
Update default log_stream port

### ISSUE THREAD

**Issue by MJJoyce** [NASA-AMMOS/AIT-Core#149]
The default log_stream in the server configuration points to the incorrect port for receiving log messages. We should update this to point to `2514`.

```
 - stream:              
    name: log_stream                
    input:                   
      - 3077
```
