### ISSUE TITLE
List plugins and streams by their names in server config

### ISSUE THREAD

**Issue by aywaldron** [NASA-AMMOS/AIT-Core#165]
Currently, accessing a plugins or streams configs from outside their creation requires iterating through the list of plugins/streams in order to find the one that matches what you're looking for, because their configs are in yaml list where every element is named `plugin` or `stream`. It would allow for easier access if they were listed by their name. 

For example, instead of 
```
    server:
         plugins:
             - plugin:
                 name: ait.gui.AITGUIPlugin
                 inputs:
                     - telem_stream
                     - log_stream
                 outputs:
                     - command_stream
```
it would be 
```
    server:
         plugins:
             - ait.gui.AITGUIPlugin:
                 inputs:
                     - telem_stream
                     - log_stream
                 outputs:
                     - command_stream
```
