### ISSUE TITLE
Server port configuration examples use wrong format

### ISSUE THREAD

**Issue by MJJoyce** [NASA-AMMOS/AIT-Core#290]
Example config.yaml
```
    inbound-streams:
            - stream:
                name: log_stream
                input:
                    - 2514

            - stream:
                name: telem_stream
                input:
                    - 3076
                handlers:
                    - name: ait.core.server.handlers.PacketHandler
                      packet: 1553_HS_Packet
```

Example in documentation
```
    - stream:
        name: log_stream
        input: 3077

    - stream:
        name: telem_port_in_stream
        input: 3076
        handlers:
            - my_custom_handlers.TestbedTelemHandler
```
