### ISSUE TITLE
Cfg directory expansion fails to handle new server additions

### ISSUE THREAD

**Issue by MJJoyce** [NASA-AMMOS/AIT-Core#306]
Noticed when working with some of the recent changes to the GUI plugin that when passing a relative directory for the static files no updates were being made to the path.

E.g.
```
    server:
        plugins:
            - plugin:
                name: ait.gui.AITGUIPlugin
                inputs:
                    - log_stream
                    - telem_stream
                outputs:
                    - command_stream
                html:
                    directory: ../gui/
```

The above results in the `html.directory` configuration value not having its path expanded like expected. After reviewing the directory expansion code it's a result of the recursion ignoring any type that isn't a dictionary when attempting to dig down into the structure. We'll need to modify this so the full config structure is parsed.
