### ISSUE TITLE
Refactor config so that databaseImpl ('datastore') is under 'database' section

### ISSUE THREAD

**Issue by nttoole** [NASA-AMMOS/AIT-Core#350]
Currently, plugins that use the database declare the database impl (currently between Influx and MySql) as part of their plugin section in the AIT config.  E.g.

```
plugins:
    - plugin:
        name: ait.core.server.plugins.openmct.AITOpenMctPlugin
        inputs:
            - telem_stream
        service_port: 8082
        debug_enabled: False
        database_enabled: True
        datastore: ait.core.db.InfluxDBBackend
```
...similar for the Data Archive Plugin.

However, once a DB instance is created, the plugin relies on the general 'database' section for database and access settings:

```
database:
     host: localhost
     port: 8086
     dbname: ait
     un: <username>
     pw: <password>
```

Now that there are two plugins that rely on a database, it seems that the `datastore` itself should also be under the '_database_' section (and if there are cases of intentionally needing two separate DB types, then that info should be included in the plugin section?)

So it would be:
```
database:
     host: localhost
     port: 8086
     dbname: ait
     un: <username>
     pw: <password>
     datastore/impl/etc: ait.core.db.InfluxDBBackend
```
