### ISSUE TITLE
Derivation inputs should be flexible

### ISSUE THREAD

**Issue by mudinthewater** [NASA-AMMOS/AIT-Core#410]
I.e. using either DN or EU from input channels, and flexible input triggering.

**Comment by MJJoyce** [comment]
You can already pass DN or EU values

```
>>> from ait.core import tlm
>>> d = b'\x00\x01\x00\x01\x00\x01\x00\x01\x00\x01'
>>> pkt_defn = tlm.getDefaultDict()['1553_HS_Packet']
>>> pkt = tlm.Packet(defn=pkt_defn, data=d)
>>> print(pkt.raw.Voltage_C)
1
>>> print(pkt.raw.Voltage_D)
1
>>> print(pkt.Volt_Diff)
0
>>> print(pkt.Voltage_C)
999
>>> print(pkt.Voltage_D)
99
>>> print(pkt.Volt_Diff_EU)
900
```

Using the following packet definition
```
- !Packet
  name: 1553_HS_Packet
  desc: Ethernet 1553 packet used to monitor telemetry in real-time
  functions:
        CurrA_Fx(dn):     (dn - 2) / 1234.0
        Difference(x,y):  x - y
        VoltCEU(dn): 1000 - dn
        VoltDEU(dn): 100 - dn

  fields:
    - !Field
      name: Voltage_A
      desc: Voltage A as a 14-bit DN.  Conversion to engineering units is TBD.
      units: Volts
      type: MSB_U16
    - !Field
      name: Voltage_B
      desc: Voltage B as a 14-bit DN.  Conversion to engineering units is TBD.
      units: Volts
      type: MSB_U16
    - !Field
      name: Voltage_C
      desc: Voltage C as a 14-bit DN.  Conversion to engineering units is TBD.
      units: Volts
      type: MSB_U16
      dntoeu:
        equation: VoltCEU(raw.Voltage_C)
    - !Field
      name: Voltage_D
      desc: Voltage D as a 14-bit DN.  Conversion to engineering units is TBD.
      units: Volts
      type: MSB_U16
      aliases:
        icd: Voltage_D_Alias
      dntoeu:
        equation: VoltDEU(raw.Voltage_D)
    - !Field
      name: Current_A
      type: MSB_U16
      dntoeu:
        equation: CurrA_Fx(raw.Current_A)
        units:    amperes

  derivations:
    - !Derivation
      name: Volt_Diff
      desc: Difference between Voltage_A and Voltage_B
      equation: Difference(raw.Voltage_A, raw.Voltage_B)
      units: Volts
      type: MSB_U16

    - !Derivation
      name: Volt_Diff_EU
      desc: Difference between Voltage_A and Voltage_B
      equation: Difference(Voltage_C, Voltage_D)
      units: Volts
      type: MSB_U16
```

Any triggering conditions supported by `!Field` are supported here. E.g., `when` clauses. If you have something specific in mind feel free to comment and we can open a ticket to track addition functionality. We'll track documentation updates related to this in a separate ticket as well.
