### ISSUE TITLE
Derivation use inputs (fields) from different packets?

### ISSUE THREAD

**Issue by perryzjc** [NASA-AMMOS/AIT-Core#500]
For my current testing, the derivation can only receive input from the current packet. If there are fields from other packets, it will throw an error, such as:
```text
AttributeError: Packet 'ABC_DEF_1' has no field ' test_field_123'
2023-08-01T07:26:04Z <Plugin name=AITGUIPlugin> failed with AttributeError
```

Below is a more detailed example of the scenario.

```yaml
- !Packet
  name: ABC_DEF_1
  functions:
        Difference(x,y):  x - y

  fields:
    - !Field
      name: Voltage_A
      units: Volts
      type: MSB_U16

  derivations:
    - !Derivation
      name: my_deriv
      equation: Difference(raw.Voltage_A, raw.ABC_DEF_2.test_field_123)
      units: Volts
      type: MSB_U16


- !Packet
  name: ABC_DEF_2

  fields:
    - !Field
      name: test_field_123
      units: Volts
      type: MSB_U16
```
In this case, I want to make a derivation that uses fields from two packets `ABC_DEF_1` and `ABC_DEF_2`

I have tried several potential formats for equations, such as <packet_name>.<field_name> or <field_name>, but none of them have worked yet. And I did not find relevant documentation about how to make a derivation that can receive inputs across different packets.

Could someone help me figure out how to do so? If this feature is not available yet, can someone implement it?
Thanks.
