### ISSUE TITLE
Cmd validation ignores CCSDS app id when reporting duplicate op codes

### ISSUE THREAD

**Issue by MJJoyce** [NASA-AMMOS/AIT-Core#73]
The Cmd validation needs to consider the CCSDS support added in a previous ticket when reporting duplicate commands or opcodes.

Snippet from ticket where support was implemented is below. Changes were added in dac25002748f46a1ae58141e0e30a059b86283e1. We need to elevate CCSDS header support in `bliss.core` to allow (optional) specification of CCSDS headers and expected values when defining telemetry packets:

```yaml
- !Packet
  name:  EHS
  desc:  Engineering Health and Status
  ccsds:
    apid: 42
  fields:
    ...
```

and commands:

```yaml
- !Command
  name:      NO_OP
  opcode:    0x00
  ccsds:     { apid: 0x06, type: 1, shflag: 1, seqflags: 0b11 }
  subsystem: CORE
  title:     No Operation
  desc:      No Operation
```
